"use strict";
(()=>{
const stage=document.querySelector('.stage');
const hero=document.createElement('header');hero.className='demo-intro';hero.innerHTML=`<a class="demo-brand" href="https://github.com/Brutal-BrutalFoundry/Cyllaris">BRUTALFOUNDRY / CYLLARIS</a><p class="eyebrow">YOUR AI. CONTROLLED LOCAL WORK.</p><h2>Keep the reasoning.<br>Cut the handoffs.</h2><p>Your AI can suggest the next step. Cyllaris is being built to carry permitted work into your files and installed tools, then return the actual results.</p><div class="intro-links"><a href="#guided-demo">Try the demo ↓</a><a href="https://github.com/Brutal-BrutalFoundry/Cyllaris#engineering-the-execution-loop">Explore the engineering ↗</a></div><p class="simulation-note">Interactive simulation using the approved Precision interface. No AI connection, terminal access or real execution. Product under development.</p>`;stage.before(hero);
const story=document.createElement('section');story.id='guided-demo';story.className='demo-story';story.setAttribute('aria-label','Guided demonstration');story.innerHTML=`<div class="story-top"><span class="eyebrow">WHY CYLLARIS?</span><span id="demo-progress"></span></div><div class="context-pick" role="group" aria-label="Project context"><button data-context="personal" aria-pressed="true">Organize files</button><button data-context="professional" aria-pressed="false">Prepare a report</button><button data-context="power" aria-pressed="false">Check a project</button></div><h2 id="demo-title"></h2><p id="demo-description"></p><section class="ai-conversation" aria-label="Simulated AI conversation"><div class="chat-heading">Your AI conversation <span>Simulated client</span></div><div id="demo-chat" aria-live="polite"></div></section><details class="more-info"><summary>More info about this task</summary><p id="demo-context"></p><div id="demo-artifact"></div><div class="extra-cases"><button id="demo-boundary">Explore permission limits</button><button id="demo-interruption">Explore interrupted delivery</button></div></details><div class="story-actions"><button id="demo-back">Previous</button><button id="demo-next">Start walkthrough</button><button id="demo-reset">Restart</button></div>`;
document.querySelector('.preview-label').before(story);
const advanced=document.createElement('details');advanced.className='advanced-options';advanced.id='advanced-controls';const advancedLabel=document.createElement('summary');advancedLabel.textContent='More interface options';advanced.append(advancedLabel);const sampleControls=document.querySelector('.preview-controls');sampleControls.before(advanced);advanced.append(sampleControls);
const foot=document.createElement('footer');foot.className='demo-footer';foot.innerHTML=`<h2>What you have seen</h2><div class="value-columns"><section><h3>Less carrying work around</h3><p>Commands and results can move through an approved task without you serving as the courier.</p></section><section><h3>Permission stays separate</h3><p>The AI proposes work. The local execution controller decides whether it is permitted.</p></section><section><h3>Outcomes stay visible</h3><p>Running a tool, delivering a result and receiving acknowledgment are separate events.</p></section></div><details><summary>Development evidence and limits</summary><p>A narrow inspect, apply and verify loop is documented in one Windows development configuration. This page is a simulation, not a recording of that run. Wider integration support, native UI binding, access-boundary examples and interruption recovery require their own qualification. Only Standard is currently qualified. Other profile labels are unavailable.</p><p>Existing tools also execute local work. Cyllaris has not yet established lower total cost, general security superiority or measured workflow savings over those tools. Local execution does not mean information sent to your chosen AI stays on the PC.</p></details><p>Cyllaris is intended for personal projects, professional work and technical workflows. No public runnable release is available.</p><a class="repo-link" href="https://github.com/Brutal-BrutalFoundry/Cyllaris">View the project on GitHub ↗</a><p class="footer-credit">Designed and built by Christopher M. / BrutalFoundry</p>`;stage.after(foot);
const $=id=>document.getElementById(id);let step=0,context='personal';
const scenarios={
personal:{title:'Organize a personal file archive',context:'Personal files / organization. Preview a naming plan, preserve originals and inspect collisions before producing an organized copy.',task:'Organize an archive copy',scope:'Selected archive copy',permission:'Read the sample manifest, create a naming plan and organized copies, verify file hashes. No deletion, original edits, network or installation.',command:'archive_sample.py',results:[['Archive inspected','Two proposed names collide. Originals remain unchanged.'],['Organized copies prepared','Collision-safe names applied in the output copy. Originals preserved.'],['Archive copy verified','Sample manifest and content hashes agree. No original file deleted.']],inspect:'Inputs: sample archive manifest\nFinding: two proposed names collide\nPlan: preserve originals; use distinct output names',change:'Before: two files would become trip-01.jpg\nAfter: trip-01-a.jpg and trip-01-b.jpg\nOutput: organized copies only; originals untouched',verify:'Sample checks: distinct names + matching content hashes\nOriginals: preserved\nImage content / metadata editing: not performed',reason:'AI can suggest names. The local-work benefit would be applying a reviewed plan across files and checking the output without manual rename-and-check cycles.'},
professional:{title:'Prepare a report from local exports',context:'Professional files / recurring reporting. Reconcile source data, surface exceptions and save a report with traceable totals.',task:'Reconcile exports and prepare a report',scope:'Selected CSV copies and report output',permission:'Read fixed-schema sample CSVs, reconcile records, save a draft and check totals. No email, upload, source edits, macros or company connectors.',command:'report_sample.py',results:[['Exports inspected','Duplicate records and a missing category require review.'],['Draft report prepared','Duplicates identified; incomplete rows listed separately. Source copies unchanged.'],['Report checks completed','Sample totals match included rows. Exceptions remain visible for human review.']],inspect:'Inputs: two sample CSV exports\nFinding: duplicate records + missing category\nPlan: retain exception list; reconcile included rows',change:'Output: draft report + exceptions.csv\nDuplicate handling: stated in the draft\nMissing categories: flagged, not guessed',verify:'Sample checks: included-row totals reconciled\nExceptions: retained for review\nBusiness accuracy / approval: not certified',reason:'AI can write a summary. The local-work benefit would be processing the actual exports, reconciling totals and creating checked outputs across a recurring reporting task.'},
power:{title:'Diagnose and check a local project',context:'Power-user projects / diagnosis. Use an installed checker, make a permitted correction and return observed verification.',task:'Verify project configuration',scope:'Disposable project copy',permission:'Inspect settings.json, correct service.port and run the known checker. No network, installation, elevation, unrelated files or app launch.',command:'project_fixture.py',results:[['Project inspected successfully','service.port is a string. No files changed.'],['Correction saved','service.port is now integer 8080. Verification is still pending.'],['Configuration verified','Saved service.port is integer 8080. App launch was not tested.']],inspect:'settings.json: service.port = "8080"\nChecker expects: integer\nSample outcome: inspected; no change yet',change:'Before: "service.port": "8080"\nAfter:  "service.port": 8080\nVerification: still required',verify:'Sample checker: configuration accepted\nApplication launch: not tested\nGeneral application repair: not established',reason:'AI can explain the error. The local-work benefit is carrying the inspection, permitted edit and checker result through the existing conversation.'}}
;
document.querySelector('#permission-content pre').nextElementSibling.textContent='Fictional commands for the selected sample task. No commands run, and no live AI proposals are read.';
const chatScenarios={personal:{request:"Organize these photos into a new folder. Keep my originals and make sure no files are lost.",proposal:"I will inspect the names first, then prepare organized copies and check them. Your original folder will stay unchanged.",finding:"Two photos would get the same name. I will use distinct names so neither is overwritten.",changed:"The organized copies are ready. I will check that their contents match the originals.",done:"Your organized folder is ready. The copies were checked, the names are distinct and your originals are unchanged."},professional:{request:"Prepare this week's report from these exports. Flag anything missing or duplicated, and check the totals.",proposal:"I will inspect the exports, prepare a draft and reconcile its totals. I will preserve the source files.",finding:"I found duplicate records and a missing category. I will list the exceptions instead of guessing.",changed:"The draft and exception list are ready. I will check the report totals against the included records.",done:"The draft report is ready and its totals reconcile. The exceptions are listed for your review; no report was sent."},power:{request:"Find the configuration problem in this project copy, make the smallest permitted fix and run the checker again.",proposal:"I will run the installed checker, propose a configuration correction and verify the saved change.",finding:"The port is stored as text but the checker expects a number. I will change that setting only.",changed:"The setting is saved as a number. I will rerun the checker before calling the task complete.",done:"The configuration check passes. Only the approved setting changed. I did not launch or retest the application."}};
const contexts=Object.fromEntries(Object.entries(scenarios).map(([k,v])=>[k,v.context]));
scenarios.support={title:'Support a workstation',context:'IT support / one selected workstation. Collect evidence, authorize a configuration repair and verify the result.',task:'Diagnose a workstation connection problem',scope:'Selected workstation sample',permission:'Read the sample application log and configuration, correct one endpoint setting and run a connection check. No remote access, administrator privileges, software installation or ticket-system connection.',command:'support_sample.py',results:[['Diagnostics collected','The application log identifies a connection failure. Its endpoint setting differs from the documented local service port.'],['Repair applied','The approved endpoint setting was corrected. A connection check is still required.'],['Connection check completed','The sample application connection check passes. The technician must confirm the user can complete their original task.']],inspect:'Evidence: sample application log + endpoint configuration\nFinding: configured endpoint differs from documented service port',change:'Approved repair: correct one endpoint setting\nNo other workstation configuration changed',verify:'Sample application connection check: passed\nOriginal user task: technician confirmation required\nCase closure: not automatic',reason:'A technician stays in their AI conversation while Cyllaris carries permitted diagnostics, a separately approved repair and a connection check. This is a single-workstation example, not remote fleet or ticket management.'};
chatScenarios.support={request:'Investigate this workstation connection problem. Show me the evidence before changing anything, and check the repair afterward.',proposal:'I will collect the permitted diagnostic evidence first. Any repair needs your permission, and I will keep a record for your case notes.',finding:'The log shows a connection failure and the endpoint differs from the documented service port. I propose correcting that setting only.',changed:'The approved setting was corrected. I will run the application connection check next.',done:'The connection check passes. The user still needs to confirm their original task works. Here are the findings, approved repair and check result for your case notes.'};
const supportButton=document.createElement('button');supportButton.dataset.context='support';supportButton.textContent='IT support';supportButton.setAttribute('aria-pressed','false');story.querySelector('.context-pick').append(supportButton);
contexts.support=scenarios.support.context;
window.cyllarisPublicSamples={scenarios,chatScenarios};
const steps=[
['The work between the answers','A helpful AI answer can still leave you running commands, applying edits and carrying results back.', 'AI suggests inspection → you run the checker\nYou copy the result → AI proposes a change\nYou apply the change → run the checker\nYou copy the result → AI continues','ready'],
['Permit a task, not unlimited access','This sample grants inspection, one configuration correction and verification in a disposable project copy.','Allowed: known checker + settings.json correction\nExcluded: other folders, network, installation, elevation\nClick Arm on the widget to explore its own walkthrough.','ready'],
['Inspect the actual project state','The sample checker identifies a type mismatch. The AI reasons from a tool result rather than an assumption.','settings.json: service.port = "8080"\nChecker expects: integer\nSample outcome: inspection succeeded; no change yet','queued'],
['Keep your conversation under your control','A result is retained while you are writing. Auto delivery and execution permission are distinct settings.','Your draft: stays untouched\nResult: retained\nDelivery: waits for an eligible input\nIllustrated behavior; loaded draft handling remains a qualification gate','queued'],
['Make the permitted correction','The configuration changes from text to an integer. A saved edit is not proof that the application works.','Before: "service.port": "8080"\nAfter:  "service.port": 8080\nVerification: still required','working'],
['Show the checked outcome','The checker accepts the saved value. The sample ends at the task boundary, with execution and delivery kept distinct.','Configuration check: passed in this simulation\nTask actions: inspect / apply / verify\nApplication launch: not tested\nComparative time or cost savings: not measured','complete'],
['What happens outside the grant?','The intended boundary refuses wider work instead of letting an AI request expand permission. This is a proposed illustration.','Proposed request: change a file outside the selected project\nIllustrated decision: refused\nAdditional access: needs a new user decision\nThis screen is not a runtime security test','ready'],
['An interruption should not repeat the change','A completed action and an unconfirmed delivery require reconciliation. Cyllaris should recover the retained result without blindly repeating work.','Execution: succeeded in the sample\nAI receipt: unconfirmed\nAutomatic retry: none\nBroader recovery: qualification required','unknown']];
function setScenario(name){$('scenario').value=name;$('scenario').dispatchEvent(new Event('change',{bubbles:true}));}
function render(){
 const s=steps[step],job=scenarios[context],chat=chatScenarios[context];
 document.dispatchEvent(new CustomEvent('cyllaris:sample-task',{detail:job}));
 const titles=['Ask your AI','Allow this task','The result returns to your AI','Your AI chooses the next step','Check the work','See the finished result','Keep work within your permission','Keep completed work when delivery breaks'];
 const descriptions=['Choose an example, then follow the conversation and Cyllaris together.','You choose what Cyllaris may do. Connecting an AI does not grant unlimited access.','Cyllaris returns the inspection result. The AI uses it to decide what to do next.','The permitted change runs locally. You do not need to carry the command and result yourself.','The AI requests a check of the saved output.','The result comes back to the conversation, with any remaining limits stated.','This extra example illustrates a request outside the permitted task.','This extra example illustrates an uncertain delivery. It is not permission to repeat completed work.'];
 $('demo-progress').textContent=step<6?`${step+1} / 6`:'Extra example';$('demo-title').textContent=titles[step];$('demo-description').textContent=descriptions[step];
 const pre=document.createElement('pre');pre.textContent=step===1?job.permission:step===2?job.inspect:step===3?job.change:step===4||step===5?job.verify:s[2];$('demo-artifact').replaceChildren(pre);
 const messages=[['You',chat.request]];
 if(step>=1)messages.push(['AI',chat.proposal]);
 if(step>=2)messages.push(['Result returned by Cyllaris',job.results[0][1]],['AI',chat.finding]);
 if(step>=4)messages.push(['Result returned by Cyllaris',job.results[1][1]],['AI',chat.changed]);
 if(step>=5)messages.push(['Result returned by Cyllaris',job.results[2][1]],['AI',chat.done]);
 if(step===6)messages.push(['AI proposal','Also change a file outside this task.'],['Cyllaris','That is outside your permission. The file is unchanged.']);
 if(step===7)messages.push(['Cyllaris','The completed result is retained. Delivery is unconfirmed; no automatic repeat is illustrated.']);
 $('demo-chat').replaceChildren(...messages.map(([who,text])=>{const row=document.createElement('div');row.className='chat-message '+(who==='You'?'from-user':who==='AI'||who==='AI proposal'?'from-ai':'from-tool');const label=document.createElement('strong');label.textContent=who;const body=document.createElement('p');body.textContent=text;row.append(label,body);return row;}));
 $('demo-back').disabled=step===0;$('demo-next').textContent=step===0?'See how it works':step>=5?'Replay':'Continue';$('demo-context').textContent=contexts[context];story.querySelectorAll('[data-context]').forEach(b=>b.setAttribute('aria-pressed',String(b.dataset.context===context)));
 $('sample-restart').click();setScenario(step===2||step===3||step===4?'working':s[3]);document.dispatchEvent(new CustomEvent('cyllaris:sample-phase',{detail:{action:step===2||step===3?1:step===4||step===5?2:0}}));
}
$('demo-next').addEventListener('click',()=>{step=step>=5?0:step+1;render();});$('demo-back').addEventListener('click',()=>{step=Math.max(0,step-1);render();});$('demo-reset').addEventListener('click',()=>{step=0;$('sample-restart').click();render();});story.querySelectorAll('[data-context]').forEach(b=>b.addEventListener('click',()=>{context=b.dataset.context;step=0;render();}));$('demo-boundary').addEventListener('click',()=>{step=6;render();});$('demo-interruption').addEventListener('click',()=>{step=7;render();});render();
})();




