"use strict";
// Public, inert workflow simulation. Timers animate sample state only.
(()=>{
const $=id=>document.getElementById(id),samples=window.cyllarisPublicSamples;
let context='personal',phase='ready',action=0,mode='auto',profile='standard',grant=null,pending=null,messages=[],timer=null,remaining=0,epoch=0,executions=0,lastChat='';
let aiRoute='cloud';
let permissionEpoch=-1,ledger=[],completed=[],extraExecutions=0,suspended=null;
function record(title,text){ledger.push([title,text]);}
function dismissConsent(){permissionEpoch=-1;boundaryEpoch=-1;if(permission.open)permission.close('cancel');if(boundary.open)boundary.close('decline');}
const routePicker=document.createElement('div');routePicker.className='ai-route-picker';routePicker.innerHTML='<label for="demo-ai-route">AI route</label><select id="demo-ai-route"><option value="cloud">Cloud AI</option><option value="local">Local AI</option></select><span>Simulated routes</span>';document.querySelector('.context-pick').after(routePicker);
const routeInfo=document.createElement('details');routeInfo.className='more-info';routeInfo.innerHTML='<summary>More info about AI routes</summary><p>Supported local models are part of Cyllaris’s intended integration scope. This demo connects to no model. A local route can avoid sending task data to a cloud model provider, but that depends on the complete model, client and tool configuration. Local hardware, inference costs and capabilities vary. Neither route changes Cyllaris’s execution permission.</p>';document.querySelector('.more-info').after(routeInfo);routeInfo.append(routePicker);
document.querySelector('.demo-intro>p:not(.eyebrow)').textContent='Cyllaris is being built to connect your chosen AI, including supported local models, with controlled work on your Windows PC. Keep your conversation and return actual tool results.';
const chat=$('demo-chat'),composer=document.createElement('div');composer.className='demo-composer';composer.innerHTML='<label for="demo-draft">Your chat input</label><textarea id="demo-draft" rows="2" placeholder="Type a draft to see Auto delivery wait"></textarea><div id="demo-pending" role="status"></div><button id="demo-send">Send result to AI</button>';chat.after(composer);
const permission=document.createElement('dialog');permission.id='demo-permission';permission.innerHTML='<form method="dialog"><h2>Allow this sample task?</h2><p id="permission-task"></p><p>Only the selected sample workspace. No deletion, network access or software installation.</p><label><input id="grant-read" type="checkbox" checked> Inspect the sample inputs</label><label><input id="grant-write" type="checkbox" checked> Create the proposed output or change</label><label><input id="grant-check" type="checkbox" checked> Check the result</label><p id="permission-limit"></p><div><button id="grant-cancel" value="cancel">Cancel</button><button id="grant-allow" value="allow">Allow sample task</button></div></form>';document.body.append(permission);
const info=document.createElement('p');info.id='workflow-note';info.className='simulation-note';info.textContent='Working browser simulation. No AI connection or local execution. Selecting a profile does not grant permission.';document.querySelector('.preview-label').after(info);
function cancelTimer(){epoch++;if(timer!==null)clearTimeout(timer);timer=null;}
function append(who,text){messages.push([who,text]);}
function setWidget(name){$('scenario').value=name;$('scenario').dispatchEvent(new Event('change',{bubbles:true}));document.dispatchEvent(new CustomEvent('cyllaris:sample-phase',{detail:{action}}));}
function reset(nextContext=context){cancelTimer();if(permission.open)permission.close('cancel');if(boundary.open)boundary.close('decline');context=nextContext;phase='ready';action=0;grant=null;pending=null;executions=0;extraExecutions=0;suspended=null;ledger=[];completed=[];messages=[];profile='standard';record('Task selected',samples.scenarios[context].task);['grant-read','grant-write','grant-check'].forEach(id=>$(id).checked=!(context==='support'&&id==='grant-write'));append('You',samples.chatScenarios[context].request);append('AI',samples.chatScenarios[context].proposal);document.dispatchEvent(new CustomEvent('cyllaris:sample-task',{detail:samples.scenarios[context]}));render();}
function render(){
const job=samples.scenarios[context];const mapped={ready:'ready',working:'working',waiting:'queued',countdown:'countdown',manual:'manual',paused:'paused',stopped:'stopped',complete:'complete',permission:'ready',unknown:'unknown',disconnected:'disconnected'};setWidget(mapped[phase]||'ready');
document.querySelector('.chat-heading').firstChild.textContent=aiRoute==='local'?'Your local AI conversation ':'Your cloud AI conversation ';$('connection-label').textContent=phase==='disconnected'?'No client':aiRoute==='local'?'Local AI sample':'Cloud AI sample';
const titles={ready:'Ready to try it?',permission:'This step needs your permission',working:'Cyllaris is doing the permitted work',waiting:'Your draft stays untouched',countdown:'Returning the result to your AI',manual:'Send the result when you are ready',paused:'The workflow is paused',stopped:'The workflow is stopped',complete:'Your AI has the checked result',unknown:'Delivery needs review',disconnected:'Connect the sample conversation'};
$('demo-title').textContent=titles[phase];$('demo-description').textContent=phase==='ready'?'Choose a task, adjust the controls if you like, then start.':phase==='permission'?'Review or change the sample permission to continue.':phase==='waiting'?'Clear your chat draft when you want the retained result delivered.':phase==='manual'?'Use Send result in the conversation. The AI receives nothing until you send.':phase==='paused'?'Completed results are retained. Resume continues without repeating them.':phase==='stopped'?'No more work will run. Restart creates a new sample task.':phase==='complete'?'Inspection, action and checking are finished in this simulation.':phase==='unknown'?'The result is retained. No automatic resend or repeat is allowed.':phase==='countdown'?`Auto delivery in ${remaining.toFixed(1)} seconds.`:'Watch the local result return to the conversation.';
$('demo-progress').textContent=phase==='complete'?'Complete':`Step ${action+1} / 3`;
const chatSnapshot=JSON.stringify(messages);if(chatSnapshot!==lastChat){lastChat=chatSnapshot;chat.replaceChildren(...messages.map(([who,text])=>{const row=document.createElement('div');row.className='chat-message '+(who==='You'?'from-user':who==='AI'?'from-ai':'from-tool');const label=document.createElement('strong');label.textContent=who;const p=document.createElement('p');p.textContent=text;row.append(label,p);return row;}));}
$('demo-context').textContent=job.context;$('demo-artifact').textContent=job.permission+'\nSample executions: '+executions+'\nAdditional comparisons: '+extraExecutions+'\nPending result: '+(pending?'retained':'none');
$('demo-pending').textContent=pending?'Retained result: '+pending.text:'No result waiting.';$('demo-send').disabled=!pending||!!$('demo-draft').value||!['manual','waiting'].includes(phase);
$('demo-interruption').disabled=!pending||!['manual','waiting','countdown'].includes(phase);$('demo-boundary').disabled=!grant||permission.open||!!suspended||!['working','manual','waiting','countdown','paused'].includes(phase);
$('demo-next').textContent=phase==='ready'?'Start task':phase==='paused'?'Resume task':phase==='complete'||phase==='stopped'?'Restart task':phase==='permission'?'Review permission':'Workflow running';$('demo-next').disabled=!['ready','paused','complete','stopped','permission'].includes(phase);$('demo-back').hidden=true;$('demo-reset').textContent='Restart';
$('primary-text').textContent=phase==='ready'?'Arm':phase==='paused'?'Resume':phase==='permission'?'Allow':phase==='complete'||phase==='stopped'?'Restart':phase==='unknown'?'Details':'Pause';$('primary').disabled=['unknown','disconnected'].includes(phase);$('primary-symbol').className=['working','waiting','countdown','manual'].includes(phase)?'play pause':'play';
const editable=['ready','paused','permission'].includes(phase);document.querySelectorAll('[data-profile]').forEach(b=>{b.disabled=false;b.setAttribute('aria-checked',String(b.dataset.profile===profile));});$('manual-mode').disabled=!editable;$('auto-mode').disabled=!editable;$('manual-mode').setAttribute('aria-pressed',String(mode==='manual'));$('auto-mode').setAttribute('aria-pressed',String(mode==='auto'));$('delay').disabled=!editable||mode==='manual';$('profile-note').textContent=profile==='trusted'?'Trusted: proposed bounded-task behavior in this simulation.':'Standard selected. Click to inspect the task permission.';
$('profile-note').textContent+=' Strict and Unrestricted: more info only.';$('delay-value').textContent=Number($('delay').value).toFixed(1)+' s';$('mode-help').textContent=mode==='manual'?'You send the retained result from the conversation.':'Auto returns results when your chat input is clear.';
document.querySelectorAll('[data-context]').forEach(b=>b.setAttribute('aria-pressed',String(b.dataset.context===context)));
if(phase==='countdown'){$('status-title').textContent='Returning result.';$('status-description').textContent=`${remaining.toFixed(1)} seconds before delivery. Typing holds it.`;}
applyEvidence();
if(phase==='permission'){$('status-title').textContent='Permission needed.';$('status-description').textContent='This operation was not included in your sample grant.';}
}
function applyEvidence(){$('connection-label').textContent=phase==='disconnected'?'No client':aiRoute==='local'?'Local AI sample':'Cloud AI sample';const last=completed.at(-1);$('outcome').hidden=!last;if(last){$('outcome-title').textContent=last.title;$('outcome-description').textContent=last.text;}
$('detail-history').replaceChildren(...ledger.map(([title,text])=>{const li=document.createElement('li');li.textContent=title+' | '+text;return li;}));
const effective=document.querySelectorAll('#permission-content h3')[2];if(effective)effective.textContent='Demo profile: '+(profile==='trusted'?'Trusted (proposed behavior)':'Standard');
if(effective)effective.nextElementSibling.textContent='Only Standard is qualified in the product. Trusted here illustrates a bounded task grant, not an enabled production policy.';
if(phase==='manual')$('status-description').textContent='Review the retained result below the conversation, then choose Send result to AI.';
if(phase==='paused')$('status-description').textContent=pending?'A result is retained. Resume continues delivery without repeating completed work.':'No result is waiting. Resume requests permission or continues the unfinished action.';
$('diagnostic-state').textContent=phase+' | Main actions: '+executions+' | Additional comparisons: '+extraExecutions+' | Pending result: '+(pending?'retained':'none');
document.querySelectorAll('[data-profile]').forEach(b=>b.setAttribute('aria-checked',String(b.dataset.profile===profile)));$('manual-mode').setAttribute('aria-pressed',String(mode==='manual'));$('auto-mode').setAttribute('aria-pressed',String(mode==='auto'));}
window.cyllarisApplyEvidence=applyEvidence;
function showPermission(){cancelTimer();permissionEpoch=epoch;$('permission-task').textContent=samples.scenarios[context].task+'. '+samples.scenarios[context].permission;$('permission-limit').textContent=profile==='trusted'?'Trusted illustrates automatic progress within a bounded grant. It is not a qualified selectable production profile.':'These choices control this browser sample only. Only Standard has current Core qualification.';if(grant){$('grant-read').checked=grant.read;$('grant-write').checked=grant.write;$('grant-check').checked=grant.check;}if(!grant){permission.setAttribute('open','');permission.classList.add('inline-consent');document.querySelector('.story-actions').before(permission);}else{permission.classList.remove('inline-consent');document.body.append(permission);permission.showModal();}}
function run(){cancelTimer();if(!grant||!grant[['read','write','check'][action]]){phase='permission';render();showPermission();return;}phase='working';render();const token=epoch;timer=setTimeout(()=>{if(token!==epoch||phase!=='working')return;timer=null;executions++;const result=samples.scenarios[context].results[action];completed.push({title:result[0],text:result[1]});record(result[0],result[1]);pending={action,text:result[1]};deliverOrHold();},900);}
function deliverOrHold(){cancelTimer();if($('demo-draft').value){phase='waiting';render();return;}if(mode==='manual'){phase='manual';render();return;}remaining=Number($('delay').value);phase='countdown';render();tick();}
function tick(){const token=epoch;timer=setTimeout(()=>{if(token!==epoch||phase!=='countdown')return;timer=null;if($('demo-draft').value){deliverOrHold();return;}const previousSecond=Math.ceil(remaining);remaining=Math.max(0,remaining-.1);if(remaining===0)deliver();else{if(Math.ceil(remaining)!==previousSecond)render();tick();}},100);}
function deliver(){if(!pending||$('demo-draft').value||['paused','stopped','unknown'].includes(phase))return;cancelTimer();const result=pending;pending=null;append('Result returned by Cyllaris',result.text);record('Result delivered',result.text);if(result.kind==='comparison'){append('AI','The separately permitted comparison found no additional differences. The original task stays paused until you resume.');pending=suspended?.pending||null;suspended=null;phase='paused';render();return;}append('AI',samples.chatScenarios[context][['finding','changed','done'][result.action]]);if(result.action===2){phase='complete';render();return;}action=result.action+1;run();}
const boundary=document.createElement('dialog');boundary.id='demo-boundary-dialog';boundary.innerHTML='<form method="dialog"><p class="eyebrow">ADDITIONAL PERMISSION</p><h2>Include another sample folder?</h2><p>The AI proposes reading a second folder to compare it with this task. That folder is outside your current permission.</p><p id="boundary-profile"></p><p>This decision covers one simulated comparison only. It does not authorize editing, deletion, network access or installation.</p><div><button value="decline" id="boundary-decline">Decline</button><button value="allow" id="boundary-allow">Allow sample comparison</button></div></form>';document.body.append(boundary);
let boundaryEpoch=-1;
function showBoundary(){if(!grant||permission.open||suspended||!['working','countdown','waiting','manual','paused'].includes(phase))return;if(['working','countdown','waiting','manual'].includes(phase)){cancelTimer();phase='paused';}boundaryEpoch=epoch;$('boundary-profile').textContent=profile==='trusted'?'Trusted does not extend a bounded task automatically. This needs a separate decision.':'Standard has not permitted this folder. You decide whether to allow the additional comparison.';boundary.returnValue='';boundary.showModal();render();}
boundary.addEventListener('close',()=>{if(boundaryEpoch!==epoch)return;boundaryEpoch=-1;const allowed=boundary.returnValue==='allow';append('AI','Compare this task with a second sample folder.');append('You',allowed?'Allowed one sample comparison. Existing task permission stays unchanged.':'Declined additional folder access.');record(allowed?'Additional permission granted':'Additional permission declined','One read-only sample comparison; existing scope unchanged.');if(!allowed){append('Cyllaris','Additional comparison blocked. No folder was read or changed.');render();return;}suspended={pending};pending=null;phase='working';cancelTimer();const token=epoch;render();timer=setTimeout(()=>{if(token!==epoch||phase!=='working')return;timer=null;extraExecutions++;const text='Sample comparison completed: no additional differences. No files changed.';completed.push({title:'Additional comparison completed',text});record('Additional comparison completed',text);pending={kind:'comparison',text};deliverOrHold();},900);});
function primary(){if(phase==='ready')showPermission();else if(phase==='permission')showPermission();else if(phase==='paused'){pending?deliverOrHold():run();}else if(['complete','stopped'].includes(phase))reset();else if(['working','waiting','countdown','manual'].includes(phase)){cancelTimer();record('Paused','Work and delivery paused.');phase='paused';render();}}
document.addEventListener('click',e=>{const b=e.target.closest('button');if(!b)return;const id=b.id,contextValue=b.dataset.context,profileValue=b.dataset.profile;const owned=['primary','stop','connect','demo-next','demo-back','demo-reset','sample-next','sample-restart','manual-mode','auto-mode','demo-boundary','demo-interruption','demo-send'];if(!contextValue&&!profileValue&&!owned.includes(id))return;e.preventDefault();e.stopImmediatePropagation();
if(contextValue){reset(contextValue);return;}if(profileValue){if(!['ready','paused','permission'].includes(phase)){append('Cyllaris','Pause before changing sample permission.');render();return;}if(['strict','unrestricted'].includes(profileValue)){append('Cyllaris',profileValue==='strict'?'Strict is a planned profile. Its production policy is not represented by this demo.':'Unrestricted has no defined, qualified Core policy. This demo will not invent unrestricted access.');render();return;}profile=profileValue;render();showPermission();return;}
if(['primary','demo-next'].includes(id))primary();else if(id==='stop'){cancelTimer();dismissConsent();record('Stopped','Further work and delivery blocked; permissions revoked.');grant=null;phase='stopped';append('Cyllaris','Sample work stopped. Completed results stay retained. Restart requires a new task permission.');render();}else if(['demo-reset','sample-restart'].includes(id))reset();else if(id==='manual-mode'||id==='auto-mode'){mode=id==='manual-mode'?'manual':'auto';render();}else if(id==='demo-send')deliver();else if(id==='demo-boundary'){showBoundary();}else if(id==='demo-interruption'){cancelTimer();dismissConsent();record('Delivery uncertain','Result retained; no automatic retry.');phase='unknown';append('Cyllaris','Sample delivery interrupted. Any completed result is retained; no automatic resend or re-execution.');render();}else if(id==='connect'){cancelTimer();dismissConsent();record('Connection changed','Task permission revoked.');phase=phase==='disconnected'?'ready':'disconnected';grant=null;render();}
},true);
document.addEventListener('keydown',e=>{if(e.key==='Escape'&&permission.open&&permission.classList.contains('inline-consent')){e.preventDefault();permission.close('cancel');}});
permission.addEventListener('close',()=>{if(permissionEpoch!==epoch)return;if(permission.returnValue!=='allow'){permissionEpoch=-1;record('Permission declined','No additional work authorized.');if(phase==='permission'){phase='paused';render();}return;}permissionEpoch=-1;grant={read:$('grant-read').checked,write:$('grant-write').checked,check:$('grant-check').checked};append('You','Allowed this sample task within the selected permissions.');record('Task permission granted','Read: '+grant.read+'; write: '+grant.write+'; check: '+grant.check);if(pending)deliverOrHold();else run();});
$('demo-draft').addEventListener('input',()=>{if(['waiting','countdown','manual'].includes(phase))deliverOrHold();else render();});
$('delay').addEventListener('input',()=>render());
$('demo-ai-route').addEventListener('change',()=>{aiRoute=$('demo-ai-route').value;reset();});
// Remove the old state picker: one workflow drives both sides of the demo.
$('scenario').closest('aside').hidden=true;
$('advanced-controls').hidden=true;
const permissionInfo=document.createElement('details');const permissionSummary=document.createElement('summary');permissionSummary.textContent='More info about permissions';permissionInfo.append(permissionSummary);$('permission-limit').before(permissionInfo);permissionInfo.append($('permission-limit'));
document.querySelector('.context-pick').id='choose-task';document.querySelector('.intro-links a').href='#choose-task';document.querySelector('.context-pick').after(document.querySelector('.story-actions'));
$('demo-draft').previousElementSibling.textContent='Draft-hold test (optional)';
$('demo-draft').placeholder='Type here to test holding a result. This does not send a message.';
reset();
})();
